### ISSUE TITLE
No info about the duplicated code

### ISSUE THREAD

**Issue by NinjaCross** [philips-software/roslyn-analyzers#102]
This is indeed a very usefull tool, I like the idea very much, but I think it's often very difficult to use.

I frequently face cases when duplicate code has been found, but I'm not able to understand to which fragment is referred, since the only information I receive is the line of code and the file name.

I just receive a message like
`MyFile.cs(164, 7): [PH2071] Duplicate code found at MyFile.cs line 51`
... but when I compare the code at line 164 with the code at line 51, I really can't find any duplication.
Simply speaking, I don't understand what the tool is telling me, to the point it's impossible to use :(

Many times it seems like I'm hitting a false-positive match scenario, but since the tool doesn't tell me which fragment is duplicated, I can't verify the hypothesis.

I strongly think that the tool should report also the matched code fragments, and not only the position.

**Comment by bcollamore** [comment]
@NinjaCross Thank you for submitting this issue.  A couple pointers:
* The duplicate code isn't based on strings, but rather C# tokens.  I.e., it's a duplicate shape detector.
* Visual Studio should put a red squiggle on the exact start of the duplication.
* One can adjust the sensitivity by configuring the token_count.

It's an interesting idea to include much more information in the diagnostic itself.  I feel like usually diagnostics are typically short and do not include code snippets, but maybe in this situation it makes sense.

Would it be possible to submit the exact code snippet from your example?  Then we can study the details and potentially improve the tool's usability.

**Comment by NinjaCross** [comment]
> @NinjaCross Thank you for submitting this issue. A couple pointers:
> 
> * The duplicate code isn't based on strings, but rather C# tokens.  I.e., it's a duplicate shape detector.

Yes, I understand, infact I was in doubt if my request was feasible :)

> * Visual Studio should put a red squiggle on the exact start of the duplication.

In my case, it's not showing any squiggle, and I sincerely was not aware that this was the expected behaviour.

> * One can adjust the sensitivity by configuring the token_count.

 Yes, that's indeed very usefull !

> It's an interesting idea to include much more information in the diagnostic itself. I feel like usually diagnostics are typically short and do not include code snippets, but maybe in this situation it makes sense.

I totally agree.

> Would it be possible to submit the exact code snippet from your example? Then we can study the details and potentially improve the tool's usability.

Unfortunately no (due to NDA restrictions) but maybe I could try to create an anonymized version of the code.

**Comment by bcollamore** [comment]
@NinjaCross 
Understood regarding NDA restrictions; if you're willing to make an anonymized version, I'd be very happy to pursue further.

I'm exploring what could be causing the missing squiggles.  I'm finding miscellaneous corruption related links online, but nothing yet that points to corruption of a specific analyzer package.  Would it be trivial to copy the offending code into a separate/new project just to see if the squiggles appear?  Also, what is your version of VS?  A colleague of mine had the same problem you were experiencing; I attributed it to "oh something is wrong with your machine", but clearly the person is not alone.  

For completeness, here are the links, but pls don't go too far on a wild goose chase:
[](https://stackoverflow.com/questions/267843/visual-studio-editor-does-not-underline-errors-anymore)
[](https://developercommunity.visualstudio.com/t/design-time-error-checking-isnt-working/113112)
And this setting:
VS2019: Tools > Options > Text Editor > General > Show error squiggles

I'll also explore the feasibility of including the offending code in the error message.  The implementation would have to re-lookup the "other" code, as only meta information is cached.  In your case it's presumably doable because the offending code is in the same compilation unit (ie., the same file).  When it's in a different compilation unit, that might be unrealistic - I'm not sure yet.

Actually, a point of clarification: the red squiggles would only appear where it was discovered.  I.e., in your case, the squiggle would start at line 164 column 7 and continue for token_count tokens.  There would not be a corresponding squiggle at line 51.  Hmmm... perhaps I could at least include the column in the meta information as well so that I could report it in the output - that should be pretty helpful.  Then you could at least definitively say: "Code starting on line 164 column 7 is shape duplicated with code on line 51 column X."

And then we could debate if we think it's actually duplicated code.  If your token_count is 100, people will tend to agree that the code could be improved - but not always.  E.g., code that is "token happy" (e.g., Moq) will trigger the analyzer more quickly.

**Comment by bcollamore** [comment]
Good news.  It's trivial to add the character information (i.e., similar to column) to the output, so that one can find the start of the duplication a little more easily.  See this picture:
<img width="689" alt="DuplicateCodeSample" src="https://user-images.githubusercontent.com/57269455/132998065-32894187-330f-49ac-82fc-cbd824dc3a16.png">
I will upload a new version of the package shortly.

Also, in lieu of squiggles, if you double-click on the finding in the Errors window, it will place the cursor at the start of where the squiggles would have been.  You should then definitively be able to identify the starting points of what the analyzer is reporting as at least token_count duplicate tokens.

I think when I merge the PR it will auto-close this issue.  We can either re-open it and maybe better to capture new issues for additional feedback (e.g., no squiggles, or doubts over if it is in fact duplicate., etc.)

**Comment by NinjaCross** [comment]
Thankyou very much for the effort !
I will try to include all the requested info/data in a few days (i'm out of office right now)

**Comment by NinjaCross** [comment]
@bcollamore I'm very sorry for the late reply, but I finally managed to get a spin again to this analyzer.
I confirm that now it shows the expected hints and pieces of duplicated code.
Thank you very much for you effort :)
I'm closing the issue.
